name: Backfill One Thread

on:
  workflow_dispatch:
    inputs:
      thread_url:
        description: 'Reddit Daily thread URL to backfill (old.reddit or www)'
        required: true

permissions:
  contents: write

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw requests flashtext

      - name: Run backfill
        env:
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: python bulk_historical_updates.py "${{ github.event.inputs.thread_url }}"

      - name: Show outputs (diagnostic)
        run: |
          echo "Repo root:" && ls -la
          echo "data/:" && ls -la data || true
          echo "corpus/:" && ls -la corpus || true
          echo "Preview a data file:" && head -n 20 data/data-*.json || true
          echo "Preview a corpus file:" && head -n 3 corpus/comments-*.jsonl || true

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add data/*.json corpus/*.jsonl manifest.json
          git commit -m "Backfill data for one thread" || echo "No changes to commit"
          git push
