name: ETH Bull-Run Predictions

on:
  schedule:
    - cron: "15 8 * * *"   # daily at 08:15 UTC (adjust as you like)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-eth-predictions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install praw requests

      - name: Run extractor
        env:
          CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: python eth_bullrun_predictions.py

      - name: Show outputs (diagnostic)
        run: |
          echo "predictions/:" && ls -la predictions || true
          echo "Manifest:" && head -n 60 predictions_manifest.json || true
          echo "Consensus:" && head -n 40 predictions/consensus.json || true

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add predictions/*.json predictions_manifest.json
          git commit -m "ETH predictions daily update" || echo "No changes to commit"
          git push
